language: go

services:
  - docker

sudo: false

os:
  - linux

env:
  global:
    - GO111MODULE=on
    - PRODUCT=copybird

go:
  - 1.12.x
dist: xenial

install:
  # Core testing install
  - docker-compose build
  - docker-compose up -d

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go build -o bin/$PRODUCT

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_deploy:
  - tar czvf build/$PRODUCT-$TRAVIS_TAG.$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH.tar.gz bin/$PRODUCT
  - docker build -t copybird/$PRODUCT:latest -t copybird/$PRODUCT:$TRAVIS_TAG .

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - build/$PRODUCT-$TRAVIS_TAG.linux-$TRAVIS_CPU_ARCH.tar.gz
      # - build/$PRODUCT-$TRAVIS_TAG.osx-$TRAVIS_CPU_ARCH.tar.gz
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: bash docker_push.sh
    on:
      tags: true