language: go

services:
  - docker

sudo: false

os:
  - linux

env:
  global:
    - GO111MODULE=on
    - PRODUCT=copybird

go:
  - 1.12.x
dist: xenial

install:
  # Core testing install
  - docker-compose build
  - docker-compose up -d

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - docker build -t copybird/copybird .

before_deploy:
  - tar czvf build/$PRODUCT-$TRAVIS_TAG.$TRAVIS_OS_NAME-$ARCH.tar.gz bin/$PRODUCT

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - build/$PRODUCT-$TRAVIS_TAG.linux-$ARCH.tar.gz
      - build/$PRODUCT-$TRAVIS_TAG.osx-$ARCH.tar.gz
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: bash docker_push.sh
    on:
      all_branches: true