/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/copybird/copybird/operator/pkg/apis/copybird/v1"
	"github.com/copybird/copybird/operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/rest"
)

// CopyBirdsGetter has a method to return a CopyBirdInterface.
// A group's client should implement this interface.
type CopyBirdsGetter interface {
	CopyBirds(namespace string) CopyBirdInterface
}

// CopyBirdInterface has methods to work with CopyBird resources.
type CopyBirdInterface interface {
	Create(*v1.CopyBird) (*v1.CopyBird, error)
	Update(*v1.CopyBird) (*v1.CopyBird, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.CopyBird, error)
	List(opts metav1.ListOptions) (*v1.CopyBirdList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CopyBird, err error)
	CopyBirdExpansion
}

// copyBirds implements CopyBirdInterface
type copyBirds struct {
	client rest.Interface
	ns     string
}

// newCopyBirds returns a CopyBirds
func newCopyBirds(c *CopybirdsV1Client, namespace string) *copyBirds {
	return &copyBirds{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the copyBird, and returns the corresponding copyBird object, and an error if there is any.
func (c *copyBirds) Get(name string, options metav1.GetOptions) (result *v1.CopyBird, err error) {
	result = &v1.CopyBird{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("copybirds").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CopyBirds that match those selectors.
func (c *copyBirds) List(opts metav1.ListOptions) (result *v1.CopyBirdList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CopyBirdList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("copybirds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested copyBirds.
func (c *copyBirds) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("copybirds").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a copyBird and creates it.  Returns the server's representation of the copyBird, and an error, if there is any.
func (c *copyBirds) Create(copyBird *v1.CopyBird) (result *v1.CopyBird, err error) {
	result = &v1.CopyBird{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("copybirds").
		Body(copyBird).
		Do().
		Into(result)
	return
}

// Update takes the representation of a copyBird and updates it. Returns the server's representation of the copyBird, and an error, if there is any.
func (c *copyBirds) Update(copyBird *v1.CopyBird) (result *v1.CopyBird, err error) {
	result = &v1.CopyBird{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("copybirds").
		Name(copyBird.Name).
		Body(copyBird).
		Do().
		Into(result)
	return
}

// Delete takes name of the copyBird and deletes it. Returns an error if one occurs.
func (c *copyBirds) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("copybirds").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *copyBirds) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("copybirds").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched copyBird.
func (c *copyBirds) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CopyBird, err error) {
	result = &v1.CopyBird{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("copybirds").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
