/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	copybirdv1 "github.com/copybird/copybird/operator/pkg/apis/copybird/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCopyBirds implements CopyBirdInterface
type FakeCopyBirds struct {
	Fake *FakeCopybirdsV1
	ns   string
}

var copybirdsResource = schema.GroupVersionResource{Group: "copybirds.copybird.org", Version: "v1", Resource: "copybirds"}

var copybirdsKind = schema.GroupVersionKind{Group: "copybirds.copybird.org", Version: "v1", Kind: "CopyBird"}

// Get takes name of the copyBird, and returns the corresponding copyBird object, and an error if there is any.
func (c *FakeCopyBirds) Get(name string, options v1.GetOptions) (result *copybirdv1.CopyBird, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(copybirdsResource, c.ns, name), &copybirdv1.CopyBird{})

	if obj == nil {
		return nil, err
	}
	return obj.(*copybirdv1.CopyBird), err
}

// List takes label and field selectors, and returns the list of CopyBirds that match those selectors.
func (c *FakeCopyBirds) List(opts v1.ListOptions) (result *copybirdv1.CopyBirdList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(copybirdsResource, copybirdsKind, c.ns, opts), &copybirdv1.CopyBirdList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &copybirdv1.CopyBirdList{ListMeta: obj.(*copybirdv1.CopyBirdList).ListMeta}
	for _, item := range obj.(*copybirdv1.CopyBirdList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested copyBirds.
func (c *FakeCopyBirds) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(copybirdsResource, c.ns, opts))

}

// Create takes the representation of a copyBird and creates it.  Returns the server's representation of the copyBird, and an error, if there is any.
func (c *FakeCopyBirds) Create(copyBird *copybirdv1.CopyBird) (result *copybirdv1.CopyBird, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(copybirdsResource, c.ns, copyBird), &copybirdv1.CopyBird{})

	if obj == nil {
		return nil, err
	}
	return obj.(*copybirdv1.CopyBird), err
}

// Update takes the representation of a copyBird and updates it. Returns the server's representation of the copyBird, and an error, if there is any.
func (c *FakeCopyBirds) Update(copyBird *copybirdv1.CopyBird) (result *copybirdv1.CopyBird, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(copybirdsResource, c.ns, copyBird), &copybirdv1.CopyBird{})

	if obj == nil {
		return nil, err
	}
	return obj.(*copybirdv1.CopyBird), err
}

// Delete takes name of the copyBird and deletes it. Returns an error if one occurs.
func (c *FakeCopyBirds) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(copybirdsResource, c.ns, name), &copybirdv1.CopyBird{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCopyBirds) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(copybirdsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &copybirdv1.CopyBirdList{})
	return err
}

// Patch applies the patch and returns the patched copyBird.
func (c *FakeCopyBirds) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *copybirdv1.CopyBird, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(copybirdsResource, c.ns, name, pt, data, subresources...), &copybirdv1.CopyBird{})

	if obj == nil {
		return nil, err
	}
	return obj.(*copybirdv1.CopyBird), err
}
