/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"time"

	copybirdv1 "github.com/copybird/copybird/operator/pkg/apis/copybird/v1"
	"github.com/copybird/copybird/operator/pkg/client/clientset/versioned"
	"github.com/copybird/copybird/operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/copybird/copybird/operator/pkg/client/listers/copybird/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"
)

// CopyBirdInformer provides access to a shared informer and lister for
// CopyBirds.
type CopyBirdInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CopyBirdLister
}

type copyBirdInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCopyBirdInformer constructs a new informer for CopyBird type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCopyBirdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCopyBirdInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCopyBirdInformer constructs a new informer for CopyBird type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCopyBirdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CopybirdsV1().CopyBirds(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CopybirdsV1().CopyBirds(namespace).Watch(options)
			},
		},
		&copybirdv1.CopyBird{},
		resyncPeriod,
		indexers,
	)
}

func (f *copyBirdInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCopyBirdInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *copyBirdInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&copybirdv1.CopyBird{}, f.defaultInformer)
}

func (f *copyBirdInformer) Lister() v1.CopyBirdLister {
	return v1.NewCopyBirdLister(f.Informer().GetIndexer())
}
